#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Aug 25 14:33:28 CST 2026
maven-metadata-activiti-releases.xml.error=
maven-metadata-activiti-releases.xml.lastUpdated=1787639608742
maven-metadata-alimaven.xml.lastUpdated=1787639608768
maven-metadata-public.xml.lastUpdated=1787639608758
